# Generated by Django 3.0.4 on 2020-03-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='dog',
        ),
    ]
